### ISSUE TITLE
Where is the EXE

### ISSUE THREAD

**Issue by danny67999** [gnas01/AssettoCorsaEnchanter#3]
i dont see an exe or anything under releases

**Comment by gnas01** [comment]
Hello, the binaries will be released in the upcoming days

**Comment by gnas01** [comment]
The binaries have been released.

**Comment by natebit98** [comment]
How do we execute this? I’m not very code savvy and don’t understand what binaries are or how to execute the code. Could you include an executable file in the master branch?

**Comment by Liinussss** [comment]
Somebody know, how i can start this ?
